### ISSUE TITLE
yapi plugin export-docx-data 安装后无效

### ISSUE THREAD

**Issue by kangming** [inceptiongt/Yapi-plugin-export-docx-data#1]
使用命令 yapi plugin export-docx-data 安装后无效
是否为安装方式不对？该如何安装？

**Comment by inceptiongt** [comment]
命令安装失败，可以试试手动安装：

1. 进入vendors文件夹，npm安装该插件。
2. 编辑config.json plugins配置项。
``````
{
  "port": "3000",
  "db": {
    "servername": "127.0.0.1",
    "DATABASE": "yapi"
  },
  ...
  "plugins": [{
    "name": "export-docx-data"，
    "options": {}
  }]
}
``````

**Comment by jasongwq** [comment]
同样出现该问题
可以通过URL访问，页面上未出现导出docx选项
https://github.com/YMFE/yapi/issues/1164#issue-461809886

**Comment by inceptiongt** [comment]
前端需要重新build，详见Yapi文档，内网部署--安装--方式二. 命令行部署

**Comment by hnxydq** [comment]
有没有详细的说明？
